### ISSUE TITLE
master up-to-date?

### ISSUE THREAD

**Issue by wernerm** [DrBenton/pymessagebus#14]
At the moment, the last commit to master was on 1 Oct 2018. 

Just wanting to check if master is actually up-to-date with your development version before I'm posting any pull requests.

@DrBenton Are you planning to potentially update master in the foreseeable future?

**Comment by jmfederico** [comment]
@wernerm I was looking at this repo, seems interesting.

Can you post the MR that you have to see if it also helps us?

Thanks!

**Comment by olivierphi** [comment]
Oh sorry folks, I completely forgot to reply to you! 🙇

The "master" branch (which I should rename "main" btw) is up-to-date yes.
This library has been used in production for a while it does the job. The thing that is really missing for now (depending on the nature of the app that is using it of course) is multithreading management for the `locking` option - in some scenarios it's useful to have such a locking in place, but only locked by thread :slightly_smiling_face:
