### ISSUE TITLE
Asynchronous mode of operation

### ISSUE THREAD

**Issue by mcejp** [DrBenton/pymessagebus#17]
Hi, from skimming the README and code, it seems that the library can only work in synchronous mode. You call `message_bus.handle` and then all the handlers are serviced serially, in the caller's thread, and their return values are collected.

Is any kind of asynchronous processing, or message passing across threads, in scope of the library?

**Comment by miguelgf** [comment]
Two different things you are mentioning here. I understand you want either to send the message to be consumed asynchronously with some broker in the middle. Having running it on threads has other different capabilities

**Comment by mcejp** [comment]
Right, but I take it the answer is _no_ :)

It turns out that my needs are quite simple, so I ended up inventing my own wheel, which is about 60 lines of code: https://gist.github.com/mcejp/148397ca415405f69bbc9b8cc0308b47
